---
title: "kachergis"
author: "Christine Soh Yue"
date: "2025-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r requirements}
require(pso)
```

# Model
copied from 
Associative Uncertainty- (Entropy) & Familiarity-Biased Model
George Kachergis  george.kachergis@gmail.com

```{r model_entropy_fn}
shannon.entropy <- function(p) {
	if (min(p) < 0 || sum(p) <= 0)
		return(NA)
	p.norm <- p[p>0]/sum(p)
	-sum(log2(p.norm)*p.norm)
}

update_known <- function(m, tr_w, tr_o) {
  startval = .01
  
  for(i in tr_w) { # for each word in the input
    for(c in 1:dim(m)[2]) { # for each column
      if(sum(m[,c]>0) & m[i,c]==0) { 
        # if the sum of the column is greater than 0 (i.e. the object has previously
        # been seen) and the word-object pair is 0, set it to the startval
        m[i,c] = startval
        # if the object is smaller than the number of rows, set the reverse
        # pairing to be the startval <-- but how do you know??
        # if(c<nrow(m)) m[c,i] = startval # Something weird is going on here
      }
    }
    for(j in tr_o) { # for each object
      if(m[i,j]==0) m[i,j] = startval # set the word, object to startval if 0
      # if the object is with a word, then set association to startval if 0
      # But how do you know that the object is the target object?
      # if(j<nrow(m) && m[j,i]==0) m[j,i] = startval # Something weird is going on here
    }
  }
  return(m)
}

get_perf <- function(m) {
  perf <- rep(0, nrow(m))
  names(perf) <- rownames(m)
  for (ref in colnames(m)) {
    if (!(ref %in% rownames(m))) {
      next
    }
    correct <- m[ref, ref]
    total <- sum(m[ref,])
    if (total == 0) {
      next
    }
    perf[ref] <- correct / total
  }
  return(perf)
}

model <- function(params, ord, reps=1, test_noise=0) {
	X <- params[1] # associative weight to distribute
	B <- params[2] # weighting of uncertainty vs. familiarity
	C <- params[3] # decay
	
	voc_sz = max(unlist(ord$words), na.rm=TRUE) # vocabulary size
	ref_sz = max(unlist(ord$objs), na.rm=TRUE) # number of objects

	traj = list()
	m <- matrix(0, voc_sz, ref_sz) # association matrix
	perf = matrix(0, reps, voc_sz) # a row for each block
	# training
	for(rep in 1:reps) { # for trajectory experiments, train multiple times
	  for(t in 1:nrow(ord$words)) {

  		tr_w = as.integer(ord$words[t,])
  		tr_w = tr_w[!is.na(tr_w)]
  		tr_o = as.integer(ord$objs[t,])
  		tr_o = tr_o[!is.na(tr_o)]
  		# print(format(tr_o, digits=3))
  		# print(format(m, digits=3, zero.print=FALSE))
  		m = update_known(m, tr_w, tr_o) # what's been seen so far?
  		# print("post update")
  		# print(format(m, digits=3, zero.print=FALSE))
  		ent_w = c() # more entropy = more dispersive
  		for(w in tr_w) { ent_w = c(ent_w, shannon.entropy(m[w,])) }
  		ent_w = exp(B*ent_w)

  		ent_o = c() # more entropy = more dispersive
  		for(o in tr_o) { ent_o = c(ent_o, shannon.entropy(m[,o])) }
  		# print(format(ent_o, digits=3))
  		ent_o = exp(B*ent_o)

  		nent = (ent_w %*% t(ent_o))
  		#nent = nent / sum(nent)
  		# get all current w,o strengths and normalize to distr X
  		assocs = m[tr_w,tr_o]
  		denom = sum(assocs * nent)
  		m = m*C # decay everything
  		# update associations on this trial
  		m[tr_w,tr_o] = m[tr_w,tr_o] + (X * assocs * (ent_w %*% t(ent_o))) / denom
  		# print(format(m, digits=3, zero.print=FALSE))

  		index = (rep-1)*length(ord$trials) + t # index for learning trajectory
  		traj[[index]] = m
	  }
	  m_test = m+test_noise # test noise constant k
	  perf[rep,] = diag(m_test) / rowSums(m_test)
	}
	want = list(perf=perf, matrix=m, traj=traj)
	return(want)
	}

```

```{r run_model}

run_model <- function(cond, parameters, print_perf=F) {
  require(pso) # or require(DEoptim)
  mod = model(parameters, ord=cond$train)
  if(print_perf) print(mod$perf)
  return(mod)
}

```

```{r fit_model}

meanSSE <- function(par, order, human_perf) {
  mod = model(par, order)
  return(sum((mod$perf-human_perf)^2))
}

fit_model <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  fits = list()
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  best <- psoptim(par_init, meanSSE, ord=order$train, human_perf=unlist(order$HumanItemAcc), lower=par_lower, upper=par_upper)
  cat(model_name,'\t',best$value,'\t',best$par,'\n')
  mod = model(best$par, ord=order$train)
  fits[[1]] = list(SSE=best$value, par=best$par, perf=mod$perf)
  stopt = Sys.time()
  print(stopt-startt)
  return(fits)
}
```

# Simulation

## Trueswell et al 2013
```{r trueswell_test}
test_model_trueswell <- function(expt, params) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[60][[1]]
  
  words = expt$train$words
  objs = expt$train$objs
  test_performance = matrix(0, 1, nrow(words))
  for(test_row in 1:nrow(words)) {
    test_options = as.integer(objs[test_row,])
    numerator = final_trajectory[test_options[1], test_options[1]]
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_options[1], option]
    }
    test_performance[1,test_row] = numerator / denominator
  }
                      
  return(test_performance)
}
```

```{r trueswell_fit_model}

meanSSE_trueswell <- function(par, order, human_perf) {
  mod = test_model_trueswell(order, par)
  return(sum((mod[1, 49:60]-human_perf)^2))
}

fit_model_trueswell <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  fits = list()
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  best <- psoptim(par_init, meanSSE_trueswell, ord=order, human_perf=unlist(order$HumanItemAcc), lower=par_lower, upper=par_upper)
  cat(model_name,'\t',best$value,'\t',best$par,'\n')
  mod = model(best$par, ord=order$train)
  fits[[1]] = list(SSE=best$value, par=best$par, perf=mod$perf)
  stopt = Sys.time()
  print(stopt-startt)
  return(fits)
}
```

```{r trueswell_words}
trueswell_words <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
                       ),
                     nrow = 60,
                     ncol = 1, byrow=T
                     )


trueswell_obj <- matrix(c(1, 5, 2, 7, 3,      2, 3, 12, 9, 6,    3, 4, 2, 8, 10,   
                          4, 7, 11, 9, 1,     5, 8, 10, 12, 6,   6, 5, 4, 11, 10, 
                          7, 11, 6, 10, 4,    8, 1, 4, 2, 3,     9, 11, 7, 2, 10, 
                          10, 8, 2, 3, 11,   11, 2, 5, 8, 7,    12, 1, 5, 10, 8, 
                          1, 6, 2, 12, 8,     2, 4, 3, 10, 11,   3, 12, 11, 9, 1, 
                          4, 12, 6, 2, 8,     5, 4, 7, 3, 2,     6, 7, 4, 3, 1, 
                          7, 3, 2, 12, 5,     8, 9, 11, 4, 6,    9, 11, 10, 5, 6, 
                          10, 1, 12, 11, 8,  11, 5, 3, 10, 9,   12, 9, 3, 2, 11,
                          1, 12, 7, 10, 9,    2, 7, 1, 10, 4,    3, 6, 9, 7, 4, 
                          4, 7, 3, 12, 1,     5, 6, 3, 7, 4,     6, 8, 7, 5, 9, 
                          7, 11, 1, 5, 9,     8, 12, 6, 10, 5,   9, 8, 2, 3, 4, 
                          10, 6, 12, 9, 1,    11, 12, 10, 6, 9,  12, 7, 8, 2, 11, 
                          1, 4, 8, 5, 3,    2, 1, 6, 8, 7,    3, 5, 12, 7, 2, 
                          4, 10, 9, 2, 5,     5, 2, 1, 8, 9,     6, 3, 12, 10, 1, 
                          7, 2, 12, 6, 9,     8, 11, 7, 5, 1,    9, 8, 12, 6, 3, 
                          10, 5, 3, 7, 4,     11, 1, 3, 6, 4,    12, 1, 6, 10, 7, 
                          1, 11, 10, 9, 6,     2, 8, 9, 11, 5,    3, 5, 11, 1, 8, 
                          4, 6, 10, 3, 11,    5, 12, 1, 11, 10,    6, 12, 8, 11, 9, 
                          7, 1, 10, 4, 8,      8, 12, 7, 2, 3,     9, 5, 4, 12, 7, 
                          10, 9, 2, 5, 4,      11, 4, 1, 2, 8,     12, 9, 6, 5, 4
                       ),
                     nrow = 60,
                     ncol = 5, byrow=T
                     )
```

```{r trueswell_run}
trueswell <- list("train" = list("words" = trueswell_words, 
                                 "objs" = trueswell_obj), 
                  "Nsubj" = 40, 
                   "Condition" = "1x2", 
                   "HumanItemAcc" = c(0.333, 0.333, 0.333, 0.333, 0.333, 0.333,
                                      0.333, 0.333, 0.333, 0.333, 0.333, 0.333)
                  # c(0.267, 0.467, 0.467, 0.333, 0.2, 0.267,
                  #                     0.333, 0.267, 0.267, 0.2, 0.333, 0.6)
                  )

trueswell_mod_fit <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
# 0.001 4.83708 1 
trueswell_mod_fit2 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit3 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))

trueswell_mod_fit4 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
# 0.001 4.83708 1 
trueswell_mod_fit5 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit6 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))

trueswell_mod_fit7 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
# 0.001 4.83708 1 
trueswell_mod_fit8 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit9 <- fit_model_trueswell("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
# 0.001 2.693656 0.9087742 
```

```{r trueswell_fit}

trueswell_mod_fit1 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit2 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit3 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit4 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit5 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit6 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit7 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit8 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
trueswell_mod_fit9 <- fit_model("kachergis", trueswell, c(.001,.1,.5), c(5,15,1))
```

```{r trueswell_results}
trueswell_results <- test_model_trueswell(trueswell, 
                                          # c(0.1080347, 12.6129, 1 )
                                          # c(0.001, 2.694, 0.909)
                                          # c(0.0138, 0.1, 0.997) # 0.333 all the way
                                          # c(0.0646, 0.1, 0.998 )
                                          c(0.02, 0.1, 0.998 )
                                          )
print("fubg")
mean(trueswell_results[1,13:60])
print("trajectory")
paste0(round(c(mean(trueswell_results[1, 1:12]), mean(trueswell_results[1, 13:24]),
  mean(trueswell_results[1, 25:36]), mean(trueswell_results[1, 37:48]),
  mean(trueswell_results[1, 49:60])), 3), collapse=", ")
```

## Yu & Yurovsky
```{r yu_yurovsky_words}
yu_yurovsky_words <- matrix(c(1, 3, 2, 11,   2, 9, 4, 5,   4, 7, 6, 1, 
                                      6, 2, 12, 3,   3, 1, 4, 12,  1, 5, 6, 8, 
                                      6, 4, 11, 2,   10, 1, 5, 3,  2, 5, 8, 4, 
                                      10, 9, 6, 2,   1, 5, 7, 11,  3, 5, 10, 6, 
                                      4, 10, 3, 5,   4, 3, 8, 1,   12, 2, 5, 8, 
                                      1, 3, 6, 12,   2, 7, 3, 4,   3, 2, 11, 8, 
                                      11, 5, 6, 4,   2, 10, 1, 4,  4, 9, 1, 12, 
                                      8, 3, 9, 6,    4, 6, 10, 7,  1, 9, 2, 6, 
                                      3, 5, 9, 7,    2, 5, 1, 7,   6, 5, 11, 12 
                       ),
                     nrow = 27,
                     ncol = 4, byrow=T
                     )
```

```{r yu_yurovsky_obj}
yu_yurovsky_obj1 <- matrix(c( 1, 11, 3, 2,    9, 5, 4, 2,      16, 6, 7, 1,
                              3, 2, 6, 12,    3, 4, 12, 1,     8, 6, 5, 1,
                              6, 4, 11, 2,    1, 3, 10, 5,     4, 8, 5, 2,
                             6, 9, 2, 10,     11, 5, 7, 1,     6, 5, 3, 10,
                             17, 10, 4, 3,    15, 8, 13, 16,   12, 14, 17, 8,
                             12, 18, 15, 13,  7, 16, 14, 15,   8, 11, 14, 15,
                             11, 17, 16, 18,  10, 14, 16, 13,  9, 12, 13, 16,
                             18, 8, 15, 9,    16, 10, 7, 18,   13, 9, 18, 14,
                             15, 7, 9, 17,    14, 17, 13, 7,    18, 11, 12, 17
                       ), 
                     nrow = 27,
                     ncol = 4, byrow=T
                     )

yu_yurovsky_obj2 <- matrix(c( 1, 11, 3, 2,    9, 5, 4, 14,     16, 6, 7, 13,
                             15, 2, 18, 12,   3, 4, 12, 1,     8, 6, 17, 13,
                             18, 16, 11, 14,  1, 15, 10, 5,    4, 8, 17, 2,
                             6, 9, 14, 10,    11, 5, 7, 13,    18, 17, 3, 10,
                             5, 10, 16, 15,   3, 8, 1, 4,      12, 2, 17, 8,
                             12, 6, 15, 13,   7, 16, 14, 3,    8, 11, 2, 15,
                             11, 5, 4, 18,    10, 14, 16, 1,   9, 12, 13, 4,
                             6, 8, 3, 9,      16, 10, 7, 18,   1, 9, 6, 2,
                             15, 7, 9, 17,    14, 5, 13, 7,    18, 11, 12, 17
                       ), 
                     nrow = 27,
                     ncol = 4, byrow=T
                     )
```

```{r yu_yurovsky_test}
test_yy_words <- matrix(c(
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6
),
nrow = 18,
ncol = 1, byrow = T)

test_yy_primacy <- matrix(c(
  1, 7, 9, 18,     2, 12, 17, 1,    3, 17, 16, 13,
  4, 10, 9, 7,     5, 4, 11, 14,    6, 10, 1, 15,
  7, 18, 8, 4,     8, 14, 11, 15,   9, 2, 17, 5,
  10, 13, 3, 2,    11, 16, 6, 12,   12, 8, 6, 15,
  # DUMMY
  1, 7, 9, 18,     2, 12, 17, 1,    3, 17, 16, 13,
  4, 10, 9, 7,     5, 4, 11, 14,    6, 10, 1, 15
),
nrow = 18,
ncol = 4, byrow = T)


test_yy_recency <- matrix(c(
  13, 7, 9, 6,    14, 12, 5, 1,     15, 17, 4, 1,
  16, 10, 9, 7,   17, 4, 11, 2,     18, 10, 1, 15,
  7, 18, 8, 4,    8, 14, 11, 3,     9, 2, 17, 5,
  10, 13, 3, 2,   11, 16, 6, 12,    12, 8, 6, 15,
  # DUMMY
  13, 7, 9, 6,    14, 12, 5, 1,     15, 17, 4, 1,
  16, 10, 9, 7,   17, 4, 11, 2,     18, 10, 1, 15
),
nrow = 18,
ncol = 4, byrow = T)

test_yy_both <- matrix(c(
  1, 13, 7, 9,     2, 14, 12, 1,     3, 15, 17, 1,
  4, 16, 10, 9,    5, 17, 4, 11,     6, 18, 10, 15,
  
  7, 18, 8, 4,     8, 14, 11, 3,     9, 2, 17, 5,
  10, 13, 3, 2,    11, 16, 6, 12,    12, 8, 6, 15,
  
  13, 1, 7, 9,     14, 2, 12, 1,     15, 3, 17, 1,
  16, 4, 10, 9,    17, 5, 4, 11,     18, 6, 10, 15
),
nrow = 18,
ncol = 4, byrow = T)
```

```{r yu_yurovsky_test}
test_model_yu_yurovsky <- function(expt, params, model, test) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[27][[1]]

  test_performance = matrix(0, 1, nrow(test_yy_words))
  for(test_row in 1:nrow(test_yy_words)) {
    if (test == "primacy") {
      test_options = as.integer(test_yy_primacy[test_row,])
    } else if (test == "recency") {
      test_options = as.integer(test_yy_recency[test_row,])
    } else {
      test_options = as.integer(test_yy_both[test_row,])
    }
    
    numerator = final_trajectory[test_yy_words[test_row,], test_yy_words[test_row,]]
    
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_yy_words[test_row,], option]
      
    }
    test_performance[1,test_row] = numerator / denominator
  }
  
  return(test_performance)
}
```

```{r yu_yurovsky_fit_model}
meanSSE_yy_primacy <- function(par, order, human_perf) {
  mod = test_model_yu_yurovsky(order, par, "kachergis", "primacy")[1:12]
  return(sum((mod-human_perf)^2))
}

meanSSE_yy_recency <- function(par, order, human_perf) {
  mod = test_model_yu_yurovsky(order, par, "kachergis", "recency")[1:12]
  return(sum((mod-human_perf)^2))
}

meanSSE_yy_both <- function(par, order, human_perf) {
  mod = test_model_yu_yurovsky(order, par, "kachergis", "both")
  return(sum((mod-human_perf)^2))
}

fit_model_yy <- function(model_name, order, par_lower, par_upper, test) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  
  for(test_row in 1:10) { 
    if (test == "primacy") {
      best <- psoptim(par_init, meanSSE_yy_primacy, ord=order, human_perf=unlist(order$HumanItemAcc), lower=par_lower, upper=par_upper) 
    } else if (test == "recency") {
      best <- psoptim(par_init, meanSSE_yy_recency, ord=order, human_perf=unlist(order$HumanItemAcc), lower=par_lower, upper=par_upper)
    } else {
      best <- psoptim(par_init, meanSSE_yy_both, ord=order, human_perf=unlist(order$HumanItemAcc), lower=par_lower, upper=par_upper)
    }
  
  cat(model_name,'\t',"recall",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}

mean_SSE_yy <- function(par, order, human_perf) {
  mod_p = test_model_yu_yurovsky(order$primacy, par, "kachergis", "primacy")[1:12]
  mod_r = test_model_yu_yurovsky(order$recency, par, "kachergis", "recency")[1:12]
  mod_b = test_model_yu_yurovsky(order$both, par, "kachergis", "both")
  
  return(sum((mod_p-order$primacy$HumanItemAcc)^2) + 
           sum((mod_r-order$recency$HumanItemAcc)^2) +
           sum((mod_b-order$both$HumanItemAcc)^2))
}

fit_model_yy_expt <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  
  for(test_row in 1:10) { 
    best <- psoptim(par_init, mean_SSE_yy, ord=order, human_perf=unlist(order$primacy$HumanItemAcc), lower=par_lower, upper=par_upper) 
    cat(model_name,'\t',"recall",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}


mean_SSE_yy_all <- function(par, order, human_perf) {
  mod_p1 = test_model_yu_yurovsky(order$primacy1, par, "kachergis", "primacy")[1:12]
  mod_r1 = test_model_yu_yurovsky(order$recency1, par, "kachergis", "recency")[1:12]
  mod_b1 = test_model_yu_yurovsky(order$both1, par, "kachergis", "both")
  mod_p2 = test_model_yu_yurovsky(order$primacy2, par, "kachergis", "primacy")[1:12]
  mod_r2 = test_model_yu_yurovsky(order$recency2, par, "kachergis", "recency")[1:12]
  mod_b2 = test_model_yu_yurovsky(order$both2, par, "kachergis", "both")
  
  return(sum((mod_p1-order$primacy1$HumanItemAcc)^2) + 
           sum((mod_r1-order$recency1$HumanItemAcc)^2) +
           sum((mod_b1-order$both1$HumanItemAcc)^2) +
           sum((mod_p2-order$primacy2$HumanItemAcc)^2) + 
           sum((mod_r2-order$recency2$HumanItemAcc)^2) +
           sum((mod_b2-order$both2$HumanItemAcc)^2))
}


fit_model_yy_all <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  
  for(test_row in 1:10) { 
    best <- psoptim(par_init, mean_SSE_yy_all, ord=order, human_perf=unlist(order$primacy$HumanItemAcc), lower=par_lower, upper=par_upper) 
    cat(model_name,'\t',"recall",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}
```

```{r yu_yurovsky_input}
# Single, Single, Single, Prim, Rec, Both
# 0.642, 0.642, 0.642, 0.580, 0.510, 0.524, 0.292,
yu_yurovsky_1_primacy <- list("train" = list("words" = yu_yurovsky_words, 
                                            "objs" = yu_yurovsky_obj1), 
                             "Nsubj" = 40, 
                             "Condition" = "1x2", 
                             "HumanItemAcc" = c(0.580, 0.580, 0.580, 0.580, 0.580, 0.580,
                                                0.642, 0.642, 0.642, 0.642, 0.642, 0.642))

yu_yurovsky_1_recency <- list("train" = list("words" = yu_yurovsky_words, 
                                            "objs" = yu_yurovsky_obj1), 
                             "Nsubj" = 40, 
                             "Condition" = "1x2", 
                             "HumanItemAcc" = c(0.510, 0.510, 0.510, 0.510, 0.510, 0.510,
                                                0.642, 0.642, 0.642, 0.642, 0.642, 0.642))

yu_yurovsky_1_both <- list("train" = list("words" = yu_yurovsky_words, 
                                            "objs" = yu_yurovsky_obj1), 
                             "Nsubj" = 40, 
                             "Condition" = "1x2", 
                             "HumanItemAcc" = c(0.524, 0.524, 0.524, 0.524, 0.524, 0.524,
                                                0.642, 0.642, 0.642, 0.642, 0.642, 0.642,
                                                0.292, 0.292, 0.292, 0.292, 0.292, 0.292))

yu_yurovsky_1_all <- list("primacy" = yu_yurovsky_1_primacy,
                          "recency" = yu_yurovsky_1_recency,
                          "both" = yu_yurovsky_1_both)

# Single, Single, Single, Prim, Rec, Both
# 0.521, 0.582, 0.575, 0.524, 0.517, 0.350, 0.377,
yu_yurovsky_2_primacy <- list("train" = list("words" = yu_yurovsky_words, 
                                            "objs" = yu_yurovsky_obj2), 
                             "Nsubj" = 40, 
                             "Condition" = "1x2", 
                             "HumanItemAcc" = c(0.524, 0.524, 0.524, 0.524, 0.524, 0.524,
                                                0.521, 0.521, 0.521, 0.521, 0.521, 0.521))

yu_yurovsky_2_recency <- list("train" = list("words" = yu_yurovsky_words, 
                                            "objs" = yu_yurovsky_obj2), 
                             "Nsubj" = 40, 
                             "Condition" = "1x2", 
                             "HumanItemAcc" = c(0.517, 0.517, 0.517, 0.517, 0.517, 0.517,
                                                0.582, 0.582, 0.582, 0.582, 0.582, 0.582))

yu_yurovsky_2_both <- list("train" = list("words" = yu_yurovsky_words, 
                                            "objs" = yu_yurovsky_obj2), 
                             "Nsubj" = 40, 
                             "Condition" = "1x2", 
                             "HumanItemAcc" = c(0.350, 0.350, 0.350, 0.350, 0.350, 0.350,
                                                0.575, 0.575, 0.575, 0.575, 0.575, 0.575,
                                                0.377, 0.377, 0.377, 0.377, 0.377, 0.377))

yu_yurovsky_2_all <- list("primacy" = yu_yurovsky_2_primacy,
                          "recency" = yu_yurovsky_2_recency,
                          "both" = yu_yurovsky_2_both)

yu_yurovsky_all <- list("primacy1" = yu_yurovsky_1_primacy,
                        "recency1" = yu_yurovsky_1_recency,
                        "both1" = yu_yurovsky_1_both,
                        "primacy2" = yu_yurovsky_2_primacy,
                        "recency2" = yu_yurovsky_2_recency,
                        "both2" = yu_yurovsky_2_both)
```

```{r yu_yurovsky_fit_expt1}

yu_yurovsky_1_p_mod_fit <- fit_model_yy("kachergis", yu_yurovsky_1_primacy, 
                                        c(.001,.1,.5), c(5,15,1), test="primacy") 
# 0.1170199 0.1000000 0.9791348 
# c(0.117, 0.1, 0.979)

yu_yurovsky_1_r_mod_fit <- fit_model_yy("kachergis", yu_yurovsky_1_recency,
                                        c(.001,.1,.5), c(5,15,1), test = "recency")
# 0.09017683 0.1 0.978612 
# c(0.090, 0.1, 0.979)

yu_yurovsky_1_b_mod_fit <- fit_model_yy("kachergis", yu_yurovsky_1_both,
                                        c(.001,.1,.5), c(5,15,1), test = "both") 
# 0.09636497 0.1 0.9909955 
# c(0.096, 0.1, 0.991)

```

```{r yu_yurovsky_fit_expt1}
yu_yurovsky_1_mod_fit <- fit_model_yy_expt("kachergis", yu_yurovsky_1_all,
                                           c(.001,.1,.5), c(5,15,1))
```

```{r yu_yurovsky_fit_expt2}
yu_yurovsky_2_p_mod_fit <- fit_model_yy("kachergis", yu_yurovsky_2_primacy, 
                                        c(.001,.1,.5), c(5,15,1), test="primacy") 
# 0.06571029 0.6911813 1 
# c(0.066, 0.691, 1)

yu_yurovsky_2_r_mod_fit <- fit_model_yy("kachergis", yu_yurovsky_2_recency,
                                        c(.001,.1,.5), c(5,15,1), test = "recency")
# 0.0808891 0.1 1 
# c(0.081, 0.1, 1)

yu_yurovsky_2_b_mod_fit <- fit_model_yy("kachergis", yu_yurovsky_2_both, c(.001,.1,.5),
                                        c(5,15,1), test = "both") 
# 0.06655082 0.1 0.9863269 
# c(0.067, 0.1, 0.986)
```

```{r yu_yurovsky_fit_expt1}
yu_yurovsky_2_mod_fit <- fit_model_yy_expt("kachergis", yu_yurovsky_2_all,
                                           c(.001,.1,.5), c(5,15,1))
```
```{r yu_yurovsky_fit_expt_all}
yu_yurovsky_mod_fit <- fit_model_yy_all("kachergis", yu_yurovsky_all,
                                           c(.001,.1,.5), c(5,15,1))
```

```{r yu_yurovsky_test}
run_yu_yurovsky_expt <- function(expt, prim_param, rec_param, both_param) {
  results = matrix(0, 1, 7)
  if(expt == 1) {
    yy_p <- test_model_yu_yurovsky(yu_yurovsky_1_primacy, prim_param, 
                                        "kachergis", "primacy")
    
    yy_r <- test_model_yu_yurovsky(yu_yurovsky_1_recency, rec_param, 
                                        "kachergis", "recency")
    
    yy_b <- test_model_yu_yurovsky(yu_yurovsky_1_both, both_param, 
                                        "kachergis", "both")
  } else {
    yy_p <- test_model_yu_yurovsky(yu_yurovsky_2_primacy, prim_param, 
                                        "kachergis", "primacy")
    
    yy_r <- test_model_yu_yurovsky(yu_yurovsky_2_recency, rec_param, 
                                        "kachergis", "recency")
    
    yy_b <- test_model_yu_yurovsky(yu_yurovsky_2_both, both_param, 
                                        "kachergis", "both")
    
  }
  results[1, 1] = mean(yy_p[7:12])
  results[1, 2] = mean(yy_r[7:12])
  results[1, 3] = mean(yy_b[7:12])
  
  results[1, 4] = mean(yy_p[1:6])
  results[1, 5] = mean(yy_r[1:6])
  results[1, 6] = mean(yy_b[1:6])
  results[1, 7] = mean(yy_b[13:18])

  return(round(results, 3))
}
```

```{r yu_yurovsky_test_results}
paste0(run_yu_yurovsky_expt(1, c(0.117, 0.1, 0.979), c(0.090, 0.1, 0.979), c(0.096, 0.1, 0.991)), collapse=", ")


paste0(run_yu_yurovsky_expt(2, c(0.0657, 0.691, 1), c(0.081, 0.1, 1), c(0.067, 0.1, 0.986)), collapse=", ")


paste0(run_yu_yurovsky_expt(1, c(0.0996, 0.1, 0.980), c(0.0996, 0.1, 0.980), c(0.0996, 0.1, 0.980)), collapse=", ")


paste0(run_yu_yurovsky_expt(2, c(0.0735, 0.155, 1), c(0.0735, 0.155, 1), c(0.0735, 0.155, 1)), collapse=", ")

# 0.08079131 0.1 0.9938189
paste0(run_yu_yurovsky_expt(1, c(0.0808, 0.1, 0.994), c(0.0808, 0.1, 0.994), c(0.0808, 0.1, 0.994)), collapse=", ")


paste0(run_yu_yurovsky_expt(2, c(0.0808, 0.1, 0.994), c(0.0808, 0.1, 0.994), c(0.0808, 0.1, 0.994)), collapse=", ")

```

## Yu & Smith
```{r yu_smith_4}
yu_smith_4_wo <- matrix(c( 1,  4,  7, 16,   2,  9, 10, 13,   5, 15, 17, 18,
                        4,  7,  9, 17,   3,  6, 12, 14,  10, 14, 16, 18,
                        6,  8, 11, 12,   1,  3, 11, 13,   9, 10, 13, 18,
                        4, 15, 16, 17,   2,  5,  8, 15,   3,  5,  7, 11,
                        7, 11, 13, 15,   3,  5,  6, 12,   9, 10, 12, 17,
                        1,  2,  8, 18,   1,  6,  8, 16,   3,  5, 10, 17,
                        1,  5, 11, 15,   1,  7, 16, 17,  13, 14, 15, 18,
                        2,  8,  9, 12,   9, 10, 13, 14,   4,  6,  7, 16, 
                        2,  8, 11, 14,   3,  4,  6, 12,   2,  4,  8, 14
                       ),
                     nrow = 27,
                     ncol = 4, byrow=T
                     )

yu_smith_4_train <- list("words" = yu_smith_4_wo, "objs" = yu_smith_4_wo)
yu_smith_4 <- list("train" = yu_smith_4_train, "Nsubj" = 40, 
                   "Condition" = "1x2", 
                   "HumanItemAcc" = c(0.53, 0.53, 0.53, 0.53, 0.53, 0.53,
                                      0.53, 0.53, 0.53, 0.53, 0.53, 0.53,
                                      0.53, 0.53, 0.53, 0.53, 0.53, 0.53))
```

```{r yu_smith_3}
yu_smith_3 <- matrix(c( 1,  6, 17,   8,  7, 15,   4, 13, 17,   3,  2, 16,
                        8,  9, 16,   1,  5, 14,   2,  9, 11,   8, 12, 13,
                        4,  7, 11,   1,  8, 10,   7,  5, 17,   3,  6, 15,
                        4,  2, 10,   3, 11, 17,   2,  5,  6,   1, 13, 15,
                        8, 14, 18,   4,  9, 15,   3, 13, 18,   5, 11, 15,
                       15, 18, 16,   5, 10, 18,   9, 12, 18,  10, 12, 17,
                        4,  5, 16,   6, 10, 13,   8, 11,  6,   2, 12, 14,
                        7,  9, 10,   1, 3,  9,    6, 14, 16,   2, 17, 18,
                        4,  3, 14,   7, 13, 14,   1, 11, 12,   7, 16, 12
                       ),
                     nrow = 36,
                     ncol = 3, byrow=T
                     )

yu_smith_3_train <- list("words" = yu_smith_3, "objs" = yu_smith_3)
yu_smith_3 <- list("train" = yu_smith_3_train, "Nsubj" = 40, 
                   "Condition" = "1x2", 
                   "HumanItemAcc" = c(0.76, 0.76, 0.76, 0.76, 0.76, 0.76, 
                                      0.76, 0.76, 0.76, 0.76, 0.76, 0.76, 
                                      0.76, 0.76, 0.76, 0.76, 0.76, 0.76))
```

```{r yu_smith_2}
yu_smith_2 <- matrix(c( 5, 10,   4,  5,   6, 15,   1,  6,  12, 15,  15, 10, 
                        7,  8,  14, 12,   7, 18,  14, 15,   1,  4,   7, 17, 
                        3, 13,  10, 17,   5,  9,  11, 18,   2,  9,  17,  2, 
                        9, 13,   7,  1,  17, 10,  13,  6,   1,  2,   3, 15, 
                        8, 11,  12,  3,  11, 12,  16,  3,   3, 14,   4, 17, 
                        2, 18,   8,  9,  11, 13,   3,  1,  13, 17,   2,  8, 
                        4,  6,   4,  7,  16, 18,   5,  1,   6, 14,  16, 10, 
                        5, 11,   7, 16,   8, 10,   2, 11,  14, 18,  12,  9, 
                       13, 16,   5,  8,   9, 14,  16, 15,   6, 12,   4, 18 
                       ),
                     nrow = 54,
                     ncol = 2, byrow=T
                     )

yu_smith_2_train <- list("words" = yu_smith_2, "objs" = yu_smith_2)
yu_smith_2 <- list("train" = yu_smith_2_train, "Nsubj" = 40, 
                   "Condition" = "1x2", 
                   "HumanItemAcc" = c(0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 
                                      0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 
                                      0.89, 0.89, 0.89, 0.89, 0.89, 0.89))
```

```{r yu_smith_fit}

yu_smith_4_mod_fit0 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit1 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit2 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit3 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit4 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit5 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit6 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit7 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit8 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_4_mod_fit9 <- fit_model("kachergis", yu_smith_4, 
                                c(.001,.1,.5), c(5,15,1))

yu_smith_3_mod_fit0 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit1 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit2 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit3 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit4 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit5 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit6 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit7 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit8 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_3_mod_fit9 <- fit_model("kachergis", yu_smith_3, 
                                c(.001,.1,.5), c(5,15,1))

yu_smith_2_mod_fit0 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit1 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit2 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit3 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit4 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit5 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit6 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit7 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit8 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))
yu_smith_2_mod_fit9 <- fit_model("kachergis", yu_smith_2, 
                                c(.001,.1,.5), c(5,15,1))

```

```{r fit_all_yu_smith}

yu_smith_all <- list("two" = yu_smith_2, "three" = yu_smith_3, "four" = yu_smith_4)

meanSSE_yu_smith <- function(par, order, human_perf) {
  mod2 = model(par, order$two$train)
  mod3 = model(par, order$three$train)
  mod4 = model(par, order$four$train)
  return(sum((mod2$perf-order$two$HumanItemAcc)^2) + 
           sum((mod3$perf-order$three$HumanItemAcc)^2) +
           sum((mod4$perf-order$four$HumanItemAcc)^2))
}

fit_model_yu_smith <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  # fits = list()
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  best <- psoptim(par_init, meanSSE_yu_smith, ord=order, human_perf=unlist(order$four$HumanItemAcc), lower=par_lower, upper=par_upper)
  cat(model_name,'\t',best$value,'\t',best$par,'\n')
  # mod = model(best$par, ord=order$train)
  # fits[[1]] = list(SSE=best$value, par=best$par, perf=mod$perf)
  stopt = Sys.time()
  print(stopt-startt)
  # return(fits)
}
```

```{r yu_smith_fit_all}

fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
fit_model_yu_smith("kachergis", yu_smith_all, c(.001,.1,.5), c(5,15,1))
```

```{r yu_smith_result_fn}
yu_smith_get_results <- function(param2, param3, param4) {
  mod4 = run_model(yu_smith_4, param4)
  mod3 = run_model(yu_smith_3, param3)
  mod2 = run_model(yu_smith_2, param2)
  
  return(paste0(round(c(mean(mod4$perf), mean(mod3$perf), mean(mod2$perf)), 3), collapse=", "))
}
```

```{r yu_smith_results}
yu_smith_get_results(c(1.023, 0.924, 0.991), c(0.569, 0.542, 0.985),
                     c(0.334, 0.348, 0.957 ))

yu_smith_get_results(c(0.3522392, 0.3298081, 0.9565753),
                     c(0.3522392, 0.3298081, 0.9565753),
                     c(0.3522392, 0.3298081, 0.9565753))
```


## Suanda et al 2014
```{r suanda_highcd}
suanda_high_cd_wo <- matrix(c(2, 1, 4, 3, 6, 7, 8, 5, 
                           1, 3, 2, 4, 7, 5, 8, 6, 
                           2, 6, 3, 7, 1, 5, 4, 8, 
                           2, 3, 5, 6, 7, 8, 1, 4
                           ),
                         nrow = 16, ncol = 2, byrow = T)

suanda_high_cd_train <- list("words" = suanda_high_cd_wo, "objs" = suanda_high_cd_wo)
suanda_high_cd <- list("train" = suanda_high_cd_train, "Nsubj" = 40, 
                   "Condition" = "1x2", 
                   "HumanItemAcc" = c(0.48, 0.48, 0.48, 0.48,
                                      0.48, 0.48, 0.48, 0.48))

suanda_med_cd_wo  <- matrix(c(2, 1, 8, 7, 3, 4, 5, 6, 
                           1, 3, 6, 7, 4, 2, 5, 8, 
                           2, 1, 7, 5, 3, 4, 6, 8, 
                           5, 6, 2, 3, 7, 8, 1, 4
                           ),
                         nrow = 16, ncol = 2, byrow = T)

suanda_med_cd_train <- list("words" = suanda_med_cd_wo, "objs" = suanda_med_cd_wo)
suanda_med_cd <- list("train" = suanda_med_cd_train, "Nsubj" = 40, 
                   "Condition" = "1x2", 
                   "HumanItemAcc" = c(0.39, 0.39, 0.39, 0.39,
                                      0.39, 0.39, 0.39, 0.39))

suanda_low_cd_wo  <- matrix(c(2, 1, 7, 8, 5, 6, 3, 4, 
                           1, 2, 5, 7, 6, 8, 3, 4,
                           1, 3, 5, 6, 7, 8, 1, 2, 
                           3, 4, 5, 6, 2, 4, 7, 8
                           ),
                         nrow = 16, ncol = 2, byrow = T)

suanda_low_cd_train <- list("words" = suanda_low_cd_wo, "objs" = suanda_low_cd_wo)
suanda_low_cd <- list("train" = suanda_low_cd_train, "Nsubj" = 40, 
                   "Condition" = "1x2", 
                   "HumanItemAcc" = c(0.34, 0.34, 0.34, 0.34,
                                      0.34, 0.34, 0.34, 0.34))
```

```{r suanda_results}

suanda_high_fit <- fit_model("kachergis", suanda_high_cd, c(.001,.1,.5), c(5,15,1))

suanda_med_fit <- fit_model("kachergis", suanda_med_cd, c(.001,.1,.5), c(5,15,1))

suanda_low_fit <- fit_model("kachergis", suanda_low_cd, c(.001,.1,.5), c(5,15,1))
```



```{r fit_all_suanda}

suanda_all <- list("high" = suanda_high_cd, "medium" = suanda_med_cd, "low" = suanda_low_cd)

meanSSE_suanda <- function(par, order, human_perf) {
  mod_hi = model(par, order$high$train)
  mod_med = model(par, order$medium$train)
  mod_lo = model(par, order$low$train)
  return(sum((mod_hi$perf-order$high$HumanItemAcc)^2) + 
           sum((mod_med$perf-order$medium$HumanItemAcc)^2) +
           sum((mod_lo$perf-order$low$HumanItemAcc)^2))
}

fit_model_suanda <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_suanda, ord=order, human_perf=unlist(order$high$HumanItemAcc), lower=par_lower, upper=par_upper)
    cat(model_name,'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}
```

```{r suanda_fit_all}
fit_model_suanda("kachergis", suanda_all, c(.001,.1,.5), c(5,15,1))
```

```{r suanda_result_fn}
suanda_get_results <- function(param4, param3, param2) {
  mod_high = run_model(suanda_high_cd, param4)
  mod_med = run_model(suanda_med_cd, param3)
  mod_low = run_model(suanda_low_cd, param2)
  
  return(paste0(round(c(mean(mod_high$perf), mean(mod_med$perf), mean(mod_low$perf)), 3), collapse=", "))
}
```


```{r suanda_run}
suanda_get_results(c(0.058, 1.871, 1), c(0.0397, 0.1, 1),
                   c(0.0348, 0.375, 1))

suanda_get_results(c(0.0442, 0.1, 0.995), c(0.0442, 0.1, 0.995),
                   c(0.0442, 0.1, 0.995))

```

# Expt 1


## Input
```{r expt1_input_words}
expt1_words <- matrix(c(51, 52, 43, 47, 43, 44, 48, 44, 45, 49, 45,
                        46, 50, 46, 53, 54, 55, 43, 56, 44, 51, 
                        52, 53, 45, 54, 46, 55, 56
                        ),
                        nrow = 28,
                        ncol=1, byrow=T
                        )

```

```{r expt1_input_recall_obj}

expt1_recall_obj <- matrix(c(39, 51, 40, 41, 
                      42, 52, 1, 2, 
                      16, 15, 43, 17, 
                      47, 27, 28, 29, NA, NA, NA, NA, 
                      44, 18, 19, 20, 
                      48, 30, 31, 32, NA, NA, NA, NA,
                      45, 21, 22, 23, 
                      49, 33, 34, 35, NA, NA, NA, NA,
                      46, 24, 25, 26, 
                      50, 36, 37, 38, NA, NA, NA, NA,
                      53, 3, 4, 5, 
                      54, 6, 7, 8, 
                      55, 9, 10, 11, NA, NA, NA, NA, 
                      56, 12, 13, 14, NA, NA, NA, NA,
                      51, 7, 1, 4, 
                      52, 33, 8, 10, 
                      53, 24, 14, 41, NA, NA, NA, NA, 
                      54, 10, 13, 16, NA, NA, NA, NA,
                      55, 19, 14, 47, 56, 25, 8, 28
                      ),
                    nrow = 28,
                    ncol=4, byrow=T
)

```

```{r expt1_input_confirm_obj}
expt1_confirm_obj <- matrix(c(39, 51, 40, 41, 
                            42, 52, 1, 2, 
                            16, 15, 43, 17, 
                            47, 27, 28, 29,
                            43, 40, 1, 28, 
                            44, 18, 19, 20, 
                            48, 30, 31, 32, 
                            44, 31, 41, 2,
                            45, 21, 22, 23, 
                            49, 33, 34, 35, 
                            45, 34, 27, 1,
                            46, 24, 25, 26, 
                            50, 36, 37, 38, 
                            46, 36, 16, 31,
                            53, 3, 4, 5, 
                            54, 6, 7, 8, 
                            55, 9, 10, 11, 
                            43, 18, 22, 4, 
                            56, 12, 13, 14,  
                            44, 21, 5, 40,
                            51, 7, 1, 4, 
                            52, 33, 8, 10, 
                            53, 24, 14, 41, 
                            45, 36, 11, 2, 
                            54, 10, 13, 16, 
                            46, 13, 7, 11,
                            55, 19, 14, 47, 56, 25, 8, 28
),
nrow = 28,
ncol=4, byrow=T
)

```

```{r expt1_input}
expt1_recall_train <- list("words" = expt1_words, "objs" = expt1_recall_obj)
expt1_recall <- list("train" = expt1_recall_train, "Nsubj" = 40, "Condition" = "1x2",
              "HumanItemAcc" = c(0.70, 0.825, 0.675, 0.775, 
                                 0.500, 0.575, 0.6, 0.5, 
                                 0.175, 0.05, 0.275, 0.15, 0.025, 0.125 ))
expt1_confirm_train <- list("words" = expt1_words, "objs" = expt1_confirm_obj)
expt1_confirm <- list("train" = expt1_confirm_train, "Nsubj" = 40, "Condition" = "1x2",
                     "HumanItemAcc" = c(0.70, 0.825, 0.675, 0.775, 
                                        0.500, 0.575, 0.6, 0.5, 
                                        0.175, 0.05, 0.275, 0.15, 0.025, 0.125 ))

expt1_input <- list("recall" = expt1_recall, "confirm" = expt1_confirm)
```

## Test
```{r expt1_test}
expt1_test <- matrix(c(
  43, 15, 16, 17, 40, 18, 23, 46, 2,
  44, 18, 19, 20, 31, 21, 26, 49, 11,
  45, 21, 22, 23, 34, 36, 17, 56, 41,
  46, 24, 25, 26, 37, 14, 20, 51, 4,
  
  47, 27, 28, 29, 2, 7, 35, 36, 16,
  48, 30, 31, 32, 8, 11, 38, 42, 41,
  49, 33, 34, 35, 1, 4, 29, 43, 28,
  50, 36, 37, 38, 28, 14, 32, 55, 40,
  
  51, 39, 40, 41, 7, 1, 12, 44, 30,
  52, 42, 1, 2, 33, 26, 21, 48, 22,
  53, 3, 4, 5, 24, 14, 6, 47, 15,
  54, 6, 7, 8, 10, 16, 42, 53, 27,
  55, 9, 10, 11, 19, 5, 39, 54, 13,
  14, 54, 55, 56, 25, 28, 51, 3, 47
),
nrow = 14,
ncol = 9, byrow = T)
```

```{r expt1_test_fn}
test_model_expt1 <- function(expt, params) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[28][[1]]

  test_performance = matrix(0, 1, 14)
  for(test_row in 1:nrow(expt1_test)) {
    test_options = as.integer(expt1_test[test_row,])
    numerator = final_trajectory[test_row+42, test_options[1]]
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_row+42, option]
    }
    test_performance[1,test_row] = numerator / denominator
  }
                      
  return(test_performance)
}
```

## Fit model

```{r expt1_fit_model}
meanSSE_expt1_condition <- function(par, order, human_perf) {
  mod = test_model_expt1(order, par)
  return(sum((mod-human_perf)^2))
}

fit_model_expt1_condition <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt1_condition, ord=order, human_perf=unlist(order$HumanItemAcc),
                    lower=par_lower, upper=par_upper)
  
    cat(model_name,'\t',"recall",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}

meanSSE_expt1 <- function(par, order, human_perf) {
  mod_confirm = test_model_expt1(order$confirm, par)
  mod_recall = test_model_expt1(order$recall, par)
  
  return(sum((mod_confirm - order$confirm$HumanItemAcc)^2) + 
           sum(mod_recall - order$recall$HumanItemAcc)^2)
}

fit_model_expt1 <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt1, ord=order, human_perf=unlist(order$recall$HumanItemAcc),
                    lower=par_lower, upper=par_upper)
  
    cat(model_name,'\t',"recall",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}
```

```{r fit_expt1}
expt1_confirm_fit <- fit_model_expt1_condition("kachergis", expt1_confirm, c(.001,.1,.5), c(5,15,1))
expt1_recall_fit <- fit_model_expt1_condition("kachergis", expt1_recall, c(.001,.1,.5), c(5,15,1))
expt1_fit <- fit_model_expt1("kachergis", expt1_input, c(.001, .1, .5), c(5, 15, 1))

```



```{r fit_expt1_prime}
test_model_expt1(expt1_confirm, c(0.1308011, 0.1, 0.9167464 ))
test_model_expt1(expt1_recall, c(5, 6.526, 0.706))
paste0(round(test_model_expt1(expt1_confirm, c(5, 6.435702, 0.9733256 )), 3), collapse=", ")
test_model_expt1(expt1_recall, c(5, 6.435702, 0.9733256 ))

                

```

# Expt 3

## Input
```{r expt3_input_words}
expt3_words <- matrix(c(63, 64, 65, 66, 67,
                        68, 69, 70, 71, 72,
                        59, 60, 61, 62,
                        59, 60, 61, 62,
                        59, 60, 61, 62,
                        63, 64, 65, 66, 67,
                        68, 69, 70, 71, 72,
                        63, 64, 65, 66, 67,
                        68, 69, 70, 71, 72
                        ),
                        nrow = 42,
                        ncol=1, byrow=T
                        )
```

```{r expt3_input_ppa_obj}
expt3_ppa_obj <- matrix(c(31, 63, 30, 29, 34, 64, 33, 32, 
                          37, 65, 36, 35, 40, 66, 39, 38,
                          43, 67, 42, 41, 46, 68, 45, 44, 
                          49, 69, 48, 47, 52, 70, 51, 50,
                          55, 71, 54, 53, 58, 72, 57, 56,
                          
                          59, 7, 6, 5, 60, 14, 13, 12,
                          61, 21, 20, 19, 62, 28, 27, 26,
                          
                          59, 30, 33, 36, 60, 39, 42, 45,
                          61, 48, 51, 54, 62, 57, 29, 32,
                          
                          4, 3, 2, 1, 11, 10, 9, 8, 
                          18, 17, 16, 15, 25, 24, 23, 22, 
                          
                          63, 3, 38, 41, 64, 44, 23, 17,
                          65, 16, 56, 4, 66, 11, 18, 25,
                          67, 47, 10, 50, 68, 24, 2, 9,
                          69, 53, 35, 1, 70, 8, 14, 22,
                          71, 14, 30, 41, 72, 28, 44, 20,
                          
                          63, 48, 13, 7, 64, 6, 51, 4,
                          65, 20, 57, 54, 66, 6, 56, 50,
                          67, 47, 27, 12, 68, 36, 11, 27,
                          69, 18, 5, 33, 70, 26, 19, 12, 
                          71, 20, 38, 29, 72, 53, 44, 25
                      ),
                    nrow = 42,
                    ncol=4, byrow=T
)

```

```{r expt3_input_app_obj}
expt3_app_obj <- matrix(c(31, 63, 30, 29, 34, 64, 33, 32, 
                          37, 65, 36, 35, 40, 66, 39, 38,
                          43, 67, 42, 41, 46, 68, 45, 44, 
                          49, 69, 48, 47, 52, 70, 51, 50,
                          55, 71, 54, 53, 58, 72, 57, 56,
                          
                          4, 3, 2, 1, 11, 10, 9, 8, 
                          18, 17, 16, 15, 25, 24, 23, 22, 
                          
                          59, 7, 6, 5, 60, 14, 13, 12,
                          61, 21, 20, 19, 62, 28, 27, 26,
                          
                          59, 30, 33, 36, 60, 39, 42, 45,
                          61, 48, 51, 54, 62, 57, 29, 32,
                          
                          63, 3, 38, 41, 64, 44, 23, 17,
                          65, 16, 56, 4, 66, 11, 18, 25,
                          67, 47, 10, 50, 68, 24, 2, 9,
                          69, 53, 35, 1, 70, 8, 14, 22,
                          71, 14, 30, 41, 72, 28, 44, 20,
                          
                          63, 48, 13, 7, 64, 6, 51, 4,
                          65, 20, 57, 54, 66, 6, 56, 50,
                          67, 47, 27, 12, 68, 36, 11, 27,
                          69, 18, 5, 33, 70, 26, 19, 12, 
                          71, 20, 38, 29, 72, 53, 44, 25
),
nrow = 42,
ncol=4, byrow=T
)

```

```{r expt3_input}
expt3_app_train <- list("words" = expt3_words, "objs" = expt3_app_obj)
expt3_app <- list("train" = expt3_app_train, "Nsubj" = 40, "Condition" = "1x2",
              "HumanItemAcc" = c(# Filler
                                 0.25, 0.275, 0.275, 0.275, 0.225, 
                                 0.2, 0.25, 0.275, 0.125, 0.15,
                                 # Target
                                 0.45, 0.275, 0.225, 0.3))
expt3_ppa_train <- list("words" = expt3_words, "objs" = expt3_ppa_obj)
expt3_ppa <- list("train" = expt3_ppa_train, "Nsubj" = 40, "Condition" = "1x2",
                     "HumanItemAcc" = c(# Filler
                                        0.268, 0.268, 0.268, 0.512, 0.268, 
                                        0.293, 0.390, 0.317, 0.220, 0.268,
                                        # Target
                                        0.292, 0.488, 0.317, 0.390))


```

## Test
```{r expt3_test}
expt3_test <- matrix(c(
  63, 31, 30, 29,  3, 38, 41, 48, 13,  7, 43, 61,
  64, 34, 33, 32, 44, 23, 17,  6, 51,  4, 67, 58,
  65, 37, 36, 35, 16, 56,  4, 20, 57, 54, 66, 55,
  66, 40, 39, 38, 11, 18, 25,  6, 56, 50, 59, 71,
  67, 43, 42, 41, 47, 10, 50, 47, 27, 12, 64, 31,
  68, 46, 45, 44, 24,  2,  9, 36, 11, 27, 60, 72,
  69, 49, 48, 47, 53, 35,  1, 18,  5, 33, 34, 62,
  70, 52, 51, 50,  8, 14, 22, 26, 19, 12, 37, 63,
  71, 55, 54, 53, 14, 30, 41, 20, 38, 29, 65, 70,
  72, 58, 57, 56, 28, 44, 20, 53, 44, 25, 40, 52,
  
  59,  7,  6,  5, 30, 33, 36,  4,  3,  2,  1, 68,
  60, 14, 13, 12, 39, 42, 45, 11, 10,  9,  8, 49,
  61, 21, 20, 19, 48, 51, 54, 18, 17, 16, 15, 69,
  62, 28, 27, 26, 57, 29, 32, 25, 24, 23, 22, 52
),
nrow = 14,
ncol = 12, byrow = T)
```

```{r expt3_test_fn}
test_model_expt3 <- function(expt, params) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[42][[1]]

  test_performance = matrix(0, 1, 14)
  for(test_row in 1:nrow(expt3_test)) {
    test_options = as.integer(expt3_test[test_row,])
    numerator = final_trajectory[test_options[1], test_options[1]]
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_options[1], option]
    }
    test_performance[1,test_row] = numerator / denominator
  }
                      
  return(test_performance)
}
```

## Fit model
```{r expt3_fit_model}
meanSSE_expt3 <- function(par, order, human_perf) {
  mod = test_model_expt3(order, par)
  return(sum((mod-human_perf)^2))
}

fit_model_expt3 <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt3, ord=order, human_perf=unlist(order$HumanItemAcc), lower=par_lower, upper=par_upper) 
    
    cat(model_name,'\t',"expt 3",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}
```

```{r fit_expt3}
expt3_app_fit <- fit_model_expt3("kachergis", expt3_app, c(.001,.1,.5), c(5,15,1)) 
# c(5, 5.495, 0.90)
# c(1.115, 4.214, 0.909)

expt3_ppa_fit <- fit_model_expt3("kachergis", expt3_ppa, c(.001,.1,.5), c(5,15,1)) 
# c(5, 6.193, 0.929)
```

## Run model
```{r expt3_run_models}
run_expt3 <- function(app_param, ppa_param) {
  app <- test_model_expt3(expt3_app, app_param)
  ppa <- test_model_expt3(expt3_ppa, ppa_param)
  
  all <- c(mean(app[11:14]), mean(app[1:10]), mean(ppa[11:14]), mean(ppa[1:10]))
  print(paste0(round(app, 3), collapse=", "))
  print(paste0(round(ppa, 3), collapse=", "))
  print(paste0(round(all, 3), collapse=", "))
  return(paste0(round(all, 3), collapse=", "))
}

run_expt3(c(5, 5.495, 0.90), c(5, 6.193, 0.929))
run_expt3(c(1.115, 4.214, 0.909), c(5, 6.193, 0.929))
run_expt3(c(5, 6.193, 0.929), c(5, 6.193, 0.929))
run_expt3(c(5, 5.495, 0.90), c(5, 5.495, 0.90))
run_expt3(c(1.11, 4.214, 0.909), c(1.11, 4.214, 0.909))
```

```{r expt3_fit_to_expt}
meanSSE_expt3_all <- function(par, order, human_perf) {
  ppa_mod = test_model_expt3(order$ppa, par)
  app_mod = test_model_expt3(order$app, par)
  return(sum((ppa_mod-order$ppa$HumanItemAcc)^2)+sum((app_mod-order$app$HumanItemAcc)^2))
}

fit_model_expt3_all <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt3_all, ord=order, human_perf=unlist(order$ppa$HumanItemAcc), lower=par_lower, upper=par_upper) 
    
    cat(model_name,'\t',"expt 3",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}

expt3_all <- list("app" = expt3_app, "ppa" = expt3_ppa)

expt3_fit <- fit_model_expt3_all("kachergis", expt3_all, c(.001,.1,.5), c(5,15,1)) 

```

```{r expt3}

run_expt3(c(5, 5.936, 0.919), c(5, 5.936, 0.919))
```

# Expt 4

## Input
```{r expt4_words}
expt4_words <- matrix(c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                        1, 2, 3, 4, 
                        1, 2, 3, 4, 
                        1, 2, 3, 4,
                        5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                        5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                        15, 16, 17, 18, 
                        15, 16, 17, 18,  
                        15, 16, 17, 18),
                      nrow = 54,
                      ncol=1, byrow=T
)

```

```{r expt4_obj}
# Same and switch are basically the same in the FUbG input,
# because there's one item that co-occurs all 3 times, one item
# that co-occurs twice, and the rest co-occur once.
expt4_obj <- matrix(c(5, 35, 36, 37,  6, 39, 40, 41,  
                     7, 43, 44, 45,  8, 47, 48, 49,
                     9, 51, 52, 53,  10, 55, 56, 57,  
                     11, 59, 60, 61,  12, 63, 64, 65, 
                     13, 67, 68, 69,  14, 71, 72, 73,  
                       
                     1, 19, 20, 21,  2, 23, 24, 25,  
                     3, 27, 28, 29,  4, 31, 32, 33,
                     1, 19, 30, 24,  2, 23, 22, 33,  
                     3, 27, 34, 21,  4, 31, 26, 29,
                     1, 27, 33, 26,  2, 19, 29, 34,  
                     3, 31, 24, 22,  4, 23, 20, 30,
                     
                     5, 36, 62, 57,  6, 40, 70, 61,   
                     7, 44, 54, 73,  8, 48, 42, 65,
                     9, 52, 66, 45,  10, 56, 38, 69,  
                     11, 60, 50, 41,  12, 64, 46, 49,
                     13, 68, 74, 37,  14, 72, 58, 53,
                     
                     5,  48, 69, 54,  6, 44, 53, 58,   
                     7, 36, 41, 50,  8, 52, 37, 46, 
                     9, 40, 61, 74,  10, 72, 45, 62,  
                     11, 64, 73, 70,  12, 68, 57, 42,
                     13, 56, 49, 66,  14, 60, 65, 38,
                       
                     15, 75, 76, 77,  16, 79, 80, 81,  
                     17, 83, 84, 85,  18, 87, 88, 89,
                     15, 75, 86, 80,  16, 79, 78, 88,  
                     17, 83, 90, 76,  18, 87, 82, 84,
                     15, 83, 88, 78,  16, 75, 84, 90,  
                     17, 87, 80, 78,  18, 83, 76, 86
                           ),
                      nrow = 54,
                      ncol=4, byrow=T
)

```

```{r expt4_input}
expt4_train <- list("words" = expt4_words, "objs" = expt4_obj)
expt4_input <- list("train" = expt4_train, "Nsubj" = 40,
                           "switch_human" = c(0.35, 0.575, 0.3, 0.275, 
                                 0.35, 0.425, 0.425, 0.4, 0.35, 
                                 0.275, 0.475, 0.475, 0.55, 0.425, 
                                 0.275, 0.325, 0.4, 0.55
                                 ),
                           "same_human" = c(0.585, 0.488, 0.756, 0.683, 
                                 0.415, 0.512, 0.39, 0.854, 0.61, 
                                 0.317, 0.902, 0.878, 0.488, 0.341, 
                                 0.39, 0.439, 0.61, 0.854
                                 ))
```

## Test
```{r expt4_test}
expt4_test_obj_same <- matrix(c(
  15, 75, 86, 82, 60, 33,  5, 10, 44,
  16, 79, 78, 90, 64,  6, 48, 11, 59,
  17, 83, 90, 78, 68, 49, 53, 32, 12,
  18, 87, 82, 86, 72, 41, 57, 13, 67,
  
   5, 35, 62, 54, 20, 45, 63, 15, 71,
   6, 39, 70, 58, 24, 60, 68, 16, 17,
   7, 43, 54, 50, 28, 55, 14, 84, 69,
   8, 47, 42, 38, 32, 25, 20, 21, 52,
   9, 51, 66, 90, 76,  1, 72, 39, 27,
  10, 55, 38, 62, 80, 49, 29, 75, 89,
  11, 59, 50, 70, 84, 31, 23, 43, 87,
  12, 63, 46, 42, 88,  3, 35, 79, 24,
  13, 67, 74, 66, 36, 19, 28, 51, 88,
  14, 71, 58, 38, 40,  4, 47, 76, 81,
  
   1, 19, 30, 26, 44,  9, 65, 80, 18,
   2, 23, 22, 34, 48, 36, 56, 77, 83,
   3, 27, 34, 22, 52, 61, 37, 73,  2,
   4, 31, 26, 30, 56, 40, 64,  7, 85
  ),
  nrow = 18,
  ncol = 9, byrow = T)

expt4_test_obj_switch <- matrix(c(
  15, 75, 86, 82, 60, 33,  5, 10, 44,
  16, 79, 78, 90, 64,  6, 48, 11, 59,
  17, 83, 90, 78, 68, 49, 53, 32, 12,
  18, 87, 82, 86, 72, 41, 57, 13, 67,
  
   5, 35, 62, 54, 20, 45, 63, 75, 71,
   6, 39, 70, 58, 24, 60, 68, 16, 83,
   7, 43, 54, 50, 28, 55, 14, 84, 69,
   8, 47, 42, 38, 32, 25, 20, 21, 52,
   9, 51, 66, 90, 76, 19, 72, 39,  3,
  10, 55, 38, 62, 80, 49, 29, 15, 89,
  11, 59, 50, 70, 84, 31,  2, 43, 18,
  12, 63, 46, 42, 88, 27, 35, 79, 24,
  13, 67, 74, 66, 36,  1, 28, 51, 88,
  14, 71, 58, 38, 40,  4, 47, 76, 81,
  
   1, 19, 30, 26, 44,  9, 65, 80, 87,
   2, 23, 22, 34, 48, 36, 56, 77, 17,
   3, 27, 34, 22, 52, 61, 37, 73, 23,
   4, 31, 26, 30, 56, 40, 64,  7, 85
  ),
  nrow = 18,
  ncol = 9, byrow = T)
```

```{r expt4_test_fn}
test_model_expt4 <- function(expt, params, same=T) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[54][[1]]

  test_performance = matrix(0, 1, 18)
  for(test_row in 1:18) {
    if(same == TRUE) {
      test_options = as.integer(expt4_test_obj_same[test_row,])
    } else {
      test_options = as.integer(expt4_test_obj_switch[test_row,])
    }
    
    numerator = final_trajectory[test_options[1], test_options[1]]
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_options[1], option]
    }
    test_performance[1,test_row] = numerator / denominator
  }
                      
  return(test_performance)
}

```

## Fit
```{r expt4_fit_fn}
meanSSE_expt4_same <- function(par, order, human_perf) {
  mod = test_model_expt4(order, par, same=TRUE)
  return(sum((mod-human_perf)^2))
}

meanSSE_expt4_switch <- function(par, order, human_perf) {
  mod = test_model_expt4(order, par, same=FALSE)
  return(sum((mod-human_perf)^2))
}

meanSSE_expt4 <- function(par, order, human_perf) {
  mod_same = test_model_expt4(order, par, same=TRUE)
  mod_switch = test_model_expt4(order, par, same=FALSE)
  return(sum((mod_same-order$same_human)^2)+
           sum((mod_switch-order$switch_human)^2))
}

fit_model_expt4 <- function(model_name, order, par_lower, par_upper, same=TRUE, expt=FALSE) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    if(expt == TRUE) {
      best <- psoptim(par_init, 
                      meanSSE_expt4, 
                      ord=order,
                      human_perf=unlist(order$same_human),
                      lower=par_lower, upper=par_upper) 
    } else{
      if(same == TRUE) {
        best <- psoptim(par_init, 
                        meanSSE_expt4_same, 
                        ord=order,
                        human_perf=unlist(order$same_human),
                        lower=par_lower, upper=par_upper) 
      } else {
        best <- psoptim(par_init, 
                        meanSSE_expt4_switch, 
                        ord=order,
                        human_perf=unlist(order$switch_human),
                        lower=par_lower, upper=par_upper) 
        
      }
    }
    
    cat(model_name,'\t',"expt 4",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}

```

```{r expt4_fit}
expt4_same_fit <- fit_model_expt4("kachergis", expt4_input, c(.001,.1,.5), c(5,15,1), same=TRUE, expt=FALSE) 

expt4_switch_fit <- fit_model_expt4("kachergis", expt4_input, c(.001,.1,.5), c(5,15,1), same=FALSE, expt=FALSE) 

expt4_fit <- fit_model_expt4("kachergis", expt4_input, c(.001,.1,.5), c(5, 15, 1), same=FALSE, expt=TRUE)
```

## Run models
```{r expt4_run_fn}
run_expt4 <- function(same_param, switch_param) {
  same <- test_model_expt4(expt4_input, same_param)
  switch <- test_model_expt4(expt4_input, switch_param)
  
  all <- c(mean(same[1:4]), mean(same[15:18]), mean(same[5:14]),
           mean(switch[1:4]), mean(switch[15:18]), mean(switch[5:14]))
  print(paste0(round(same, 3), collapse=", "))
  print(paste0(round(switch, 3), collapse=", "))
  return(paste0(round(all, 3), collapse=", "))
}

```

```{r expt4_run}
print("tuned to each condition")
run_expt4(c(0.140, 0.1, 0.895), c(0.0467, 0.1, 0.975))

print("tuned to expt")
run_expt4(c(0.0765, 0.1, 0.936),c(0.0765, 0.1, 0.936))
```

