---
title: "expt4_analysis"
author: "Christine Soh Yue"
date: "2025-10-07"
output: html_document
---

# Set-up and libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r library, results=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(ggpattern)
library(lme4)
library(lmerTest)
library(ggsignif)
library(penngradlings)

theme_set(theme_pgl_minimal())

`%!in%` <- Negate(`%in%`)

c2 <- contr.treatment(2)
coding2 <- matrix(rep(1/2, 2), ncol=1)
simple2 <- c2-coding2

expt4_model_order <- c("Human", "MIGHT", "Pursuit", "FUb", "FUb-fixed")
```

# Models

```{r expt4_models}
expt4_models <- read_csv("../model_code/results/might_expt4_results.csv") %>%
  rbind(read_csv("../model_code/results/pursuit_expt4_results.csv")) %>%
  mutate(
    block = case_when(
      substr(word, 1, 1) %in% c("f", "F") ~ "flush",
      substr(word, 1, 1) %in% c("t", "T") ~ "postflush",
      substr(word, 1, 1) %in% c("p", "P") ~ "preflush"
    ),
    word_type = case_when(
      block == "flush" ~ "Filler", 
      TRUE ~ "Target"
    )
  )
  
expt4_model_learning_selection <- expt4_models %>%
  filter(phase == "learning") %>%
  pivot_wider(
    id_cols = c(subject, word, phase, block, condition, model),
    names_from = exposure,
    values_from = c(accuracy, selection)
  ) %>%
  mutate(
    num_selections = `accuracy_1` + `accuracy_2` + `accuracy_3`,
    hypotheses = paste(selection_1, selection_2, selection_3),
    test_comp = paste(subject, word, model)
  ) %>%
  filter(num_selections > 0)
  
expt4_model_test <- expt4_models %>%
  filter(phase == "testing") %>%
  mutate(
    test_comp = paste(subject, word, model)
  ) %>%
  filter(
    test_comp %in% expt4_model_learning_selection$test_comp
  ) %>%
  left_join(expt4_model_learning_selection, by=c("test_comp", "subject", "word", "condition", "block",
                                                 "phase", "model")) 
  
expt4_fubg <- tibble(
  "condition" = c("same", "same", "same", 
                  "switch", "switch", "switch", 
                  "same", "same", "same", 
                  "switch", "switch", "switch"), 
  "model" = c("FUb", "FUb", "FUb", "FUb", "FUb", "FUb", 
             "FUb-fixed", "FUb-fixed", "FUb-fixed", "FUb-fixed", "FUb-fixed", "FUb-fixed"), 
  "block" = c("pre-flush", "flush", "post-flush", 
                  "pre-flush", "flush", "post-flush", 
                  "pre-flush", "flush", "post-flush", 
                  "pre-flush", "flush", "post-flush"), 
  "word_type" = c("Target", "Filler", "Target", "Target", "Filler", "Target",
                  "Target", "Filler", "Target", "Target", "Filler", "Target"),
  "count" = c(1, 1, 1, 1, 1, 1, 
              1, 1, 1, 1, 1, 1), 
  "mean_acc" = c(0.601, 0.602, 0.587, 0.362, 0.382, 0.42,
                 0.474, 0.485, 0.504, 0.474, 0.485, 0.504), 
  "sd_acc" = c(0, 0, 0, 0, 0, 0, 
               0, 0, 0, 0, 0, 0), 
  "se_acc" = c(0, 0, 0, 0, 0, 0,
               0, 0, 0, 0, 0, 0)
)

expt4_model_aggr_test <- expt4_model_test  %>%
  group_by(
    condition, model, block, word_type
  ) %>%
  summarise(
    count = n(),
    mean_acc = mean(accuracy),
    sd_acc = sd(accuracy),
    se_acc = sd_acc / sqrt(count)
  ) %>%
  ungroup() %>%
  rbind(expt4_fubg) %>%
  filter(
    block != "flush"
  ) %>%
  mutate(
    block = factor(case_when(
      block %in% c('preflush', 'pre-flush') ~ 'pre-flush',
      block %in% c('postflush', 'post-flush') ~ 'post-flush'
    ), levels=c('pre-flush', 'post-flush'))
  )
```

# Experiment 4

```{r expt4_data}
expt4_data <- read_csv("expt4_data.csv") %>%
  mutate(expt = 4, id = redcap_id, model = "Human")
```

```{r expt4_model_training}
expt4_by_item <- expt4_data %>%
  filter(phase == "testing") %>%
  group_by(condition, word, word_i, word_type) %>%
  summarise(mean = mean(accuracy))

paste0(round(filter(expt4_by_item, condition == "same")$mean, 3), collapse=", ")
paste0(round(filter(expt4_by_item, condition == "switch")$mean, 3), collapse=", ")
```


```{r expt4_counts}
expt4_data %>%
  group_by(condition) %>%
  summarise(
    count = n_distinct(id)
  )
```

## Testing
```{r expt4_testing}
expt4_testing <- expt4_data %>%
  filter(
    phase == "testing"
  ) %>%
  mutate(
    num_selections = as.integer(correct1) + as.integer(correct2) + 
      as.integer(correct3)
  ) 

expt4_filtered_test <- expt4_testing %>%
  filter(
    (condition == "same" & word_type == "Target" & num_selections > 2) | 
      (condition == "switch" & word_type == "Target" & num_selections >= 1) |
      (word_type == "Filler" & num_selections >= 1) 
  )
```

```{r expt4_test_figure}
expt4_aggr_test <- expt4_filtered_test %>%
  group_by(
    condition, word_type, block
  ) %>%
  summarise(
    count = n(),
    mean_acc = mean(accuracy),
    sd_acc = sd(accuracy),
    se_acc = sd_acc / sqrt(count)
  ) %>%
  ungroup() %>%
  mutate(
    word_type = factor(word_type, levels = c("Target", "Filler")),
    block = factor(block, levels = c("pre-flush", "post-flush"))
  ) 

expt4_test_all <- expt4_aggr_test %>%
  mutate(
    model = "Human",
    participant = "human"
  ) %>%
  rbind(mutate(expt4_model_aggr_test, participant = "model")) %>%
  mutate(
    model_g = factor(case_when(
      model == "pursuit" ~ "Pursuit",
      model == "might" ~ "MIGHT",
      model == "Human" ~ "Human",
      TRUE ~ model
    ), levels = expt4_model_order
    )
  )

ggplot(filter(expt4_test_all, word_type == "Target"), 
       aes(x=condition, y=mean_acc, fill=block
                                    )) +
  geom_col_pattern(aes(pattern = participant), position="dodge") +
  scale_pattern_manual(values=c("wave",
                                "stripe"), guide="none") +
  ylim(0, 1) +
  labs(
      x = "Experimental Condition",
      y = "Accuracy at test",
      fill = "Word type"
    ) +
  facet_grid(cols=vars(model_g)) +
  geom_errorbar(aes(x=condition, ymin=mean_acc+se_acc,
                    ymax=mean_acc-se_acc),
                width=.2,
                position=position_dodge(.9)) +
  scale_fill_manual(values=
                      # col2grey(
                        c(#5f1c99", 
                          "#b2abd2",
                          # "#fbd863",
                          "#e66101")
                        # )
                    # , guide = "none"
                    ) +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=16,face="bold"),
        legend.title=element_text(size=16, face="bold"),
        legend.text=element_text(size=14),
        title=element_text(size=16,face="bold"),
        strip.text.x = element_text(size = 14),
        legend.position = "bottom"
        ) +
  geom_hline(yintercept=(1/9), linetype='dotted') 

```

### Statistical analysis
```{r expt4_testing_model}
expt4_test_model_data <- expt4_filtered_test %>%
  filter(word_type == "Target") %>%
  mutate(
    condition = factor(condition, levels = c("switch", "same")),
    block = factor(block, levels = c("pre-flush", "post-flush")),
    noun = factor(word),
    offset = 1/12,
    id = factor(paste(redcap_id, condition))
  ) 

expt4_test_model_data %>% group_by(condition, block, num_selections) %>%summarise(count = n())

contrasts(expt4_test_model_data$condition) <- simple2
contrasts(expt4_test_model_data$block) <- simple2

expt4_model <- glmer(accuracy ~ condition * block + + (1 + block || id) +  offset(log(offset/(1 - offset))),
               data=expt4_test_model_data,
                           family="binomial", control=glmerControl(optimizer="bobyqa"))
summary(expt4_model)
```

## Learning
```{r expt4_learning}
expt4_data %>%
  filter(
    phase == "testing"
  ) %>%
  mutate(
    num_selections = as.integer(correct1) + as.integer(correct2) + 
      as.integer(correct3)
  ) %>%
  group_by(
    condition, num_selections, block
  ) %>%
  summarise(
    count = n()
  ) %>%
  ungroup() %>%
  filter(block != "flush")
```

```{r expt4_learning_hyp}
expt4_data %>%
  filter(
    phase == "learning"
  ) %>%
  filter(
    exposure == 3
  ) %>%
  mutate(
    previous_correct = case_when(
      exposure == 1 ~ NA,
      exposure == 2 ~ correct1,
      exposure == 3 ~ correct2
    )
  ) %>%
  filter(
    exposure == 3,
    condition == "switch" | previous_correct == 1
  ) %>%
  group_by(
    condition,
    # block, 
    previous_correct
  ) %>%
  summarise(
    count = n(),
    mean_acc = mean(accuracy)
  ) %>%
  ungroup() 
```

