---
title: "FUb experiments"
author: "Christine Soh Yue"
date: "2025-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Model
These models are copied from Kachergis' word github. There is one modification
that we make -- to remove the cross-initialization that results in a 
target-referent bias in the first exposure.
```{r model}
source("kachergis.R")
```

# Experiments

## Expt 1

### Input
```{r expt1_input_words}
expt1_words <- matrix(c(51, 52, 43, 47, 43, 44, 48, 44, 45, 49, 45,
                        46, 50, 46, 53, 54, 55, 43, 56, 44, 51, 
                        52, 53, 45, 54, 46, 55, 56
                        ),
                        nrow = 28,
                        ncol=1, byrow=T
                        )

```

```{r expt1_input_recall_obj}

expt1_recall_obj <- matrix(c(39, 51, 40, 41, 
                      42, 52, 1, 2, 
                      16, 15, 43, 17, 
                      47, 27, 28, 29, NA, NA, NA, NA, 
                      44, 18, 19, 20, 
                      48, 30, 31, 32, NA, NA, NA, NA,
                      45, 21, 22, 23, 
                      49, 33, 34, 35, NA, NA, NA, NA,
                      46, 24, 25, 26, 
                      50, 36, 37, 38, NA, NA, NA, NA,
                      53, 3, 4, 5, 
                      54, 6, 7, 8, 
                      55, 9, 10, 11, NA, NA, NA, NA, 
                      56, 12, 13, 14, NA, NA, NA, NA,
                      51, 7, 1, 4, 
                      52, 33, 8, 10, 
                      53, 24, 14, 41, NA, NA, NA, NA, 
                      54, 10, 13, 16, NA, NA, NA, NA,
                      55, 19, 14, 47, 56, 25, 8, 28
                      ),
                    nrow = 28,
                    ncol=4, byrow=T
)

expt1_confirm_obj <- matrix(c(39, 51, 40, 41, 
                            42, 52, 1, 2, 
                            16, 15, 43, 17, 
                            47, 27, 28, 29,
                            43, 40, 1, 28, 
                            44, 18, 19, 20, 
                            48, 30, 31, 32, 
                            44, 31, 41, 2,
                            45, 21, 22, 23, 
                            49, 33, 34, 35, 
                            45, 34, 27, 1,
                            46, 24, 25, 26, 
                            50, 36, 37, 38, 
                            46, 36, 16, 31,
                            53, 3, 4, 5, 
                            54, 6, 7, 8, 
                            55, 9, 10, 11, 
                            43, 18, 22, 4, 
                            56, 12, 13, 14,  
                            44, 21, 5, 40,
                            51, 7, 1, 4, 
                            52, 33, 8, 10, 
                            53, 24, 14, 41, 
                            45, 36, 11, 2, 
                            54, 10, 13, 16, 
                            46, 13, 7, 11,
                            55, 19, 14, 47, 56, 25, 8, 28
),
nrow = 28,
ncol=4, byrow=T
)

```

```{r expt1_input}
expt1_recall <- list("train" = list("words" = expt1_words, 
                                    "objs" = expt1_recall_obj), 
                     "Nsubj" = 40, "Condition" = "Expt1 Recall",
                     "HumanItemAcc" = c(0.675, 0.825, 0.775, 0.700, 
                                        0.600, 0.500, 0.575, 0.5, 
                                        0.15, 0.05, 0.125, 0.025, 0.275, 0.175))
expt1_confirm_train <- 
expt1_confirm <- list("train" = list("words" = expt1_words, 
                                     "objs" = expt1_confirm_obj), 
                      "Nsubj" = 40, "Condition" = "Expt1 Confirm",
                      "HumanItemAcc" = c(0.90697674, 0.86046512, 0.88372093, 0.79069767, 
                                        0.53488372, 0.69767442, 0.58139535, 0.46511628, 
                                        0.02325581, 0.13953488, 0.02325581, 0.04651163, 0.23255814, 0.18604651 ))

expt1_input <- list("recall" = expt1_recall, "confirm" = expt1_confirm, "Condition" = "Expt 1")
```

### Test
```{r expt1_test}
expt1_test <- matrix(c(
  43, 15, 16, 17, 40, 18, 23, 46, 2,
  44, 18, 19, 20, 31, 21, 26, 49, 11,
  45, 21, 22, 23, 34, 36, 17, 56, 41,
  46, 24, 25, 26, 37, 14, 20, 51, 4,
  
  47, 27, 28, 29, 2, 7, 35, 36, 16,
  48, 30, 31, 32, 8, 11, 38, 42, 41,
  49, 33, 34, 35, 1, 4, 29, 43, 28,
  50, 36, 37, 38, 28, 14, 32, 55, 40,
  
  51, 39, 40, 41, 7, 1, 12, 44, 30,
  52, 42, 1, 2, 33, 26, 21, 48, 22,
  53, 3, 4, 5, 24, 14, 6, 47, 15,
  54, 6, 7, 8, 10, 16, 42, 53, 27,
  55, 9, 10, 11, 19, 5, 39, 54, 13,
  56, 54, 55, 14, 25, 28, 51, 3, 47
),
nrow = 14,
ncol = 9, byrow = T)
```

```{r expt1_test_fn}
test_model_expt1 <- function(expt, params) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[28][[1]]

  test_performance = matrix(0, 1, 14)
  for(test_row in 1:nrow(expt1_test)) {
    test_options = as.integer(expt1_test[test_row,])
    numerator = final_trajectory[test_row+42, test_options[1]]
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_row+42, option]
    }
    test_performance[1,test_row] = numerator / denominator
  }
                      
  return(test_performance)
}
```

### Fit model

```{r expt1_fit_model}
meanSSE_expt1_condition <- function(par, order, human_perf) {
  mod = test_model_expt1(order, par)
  return(sum((mod-human_perf)^2))
}

fit_model_expt1_condition <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt1_condition, ord=order, human_perf=unlist(order$HumanItemAcc),
                    lower=par_lower, upper=par_upper)
  
    cat(model_name,'\t',order$Condition,'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}

meanSSE_expt1 <- function(par, order, human_perf) {
  mod_confirm = test_model_expt1(order$confirm, par)
  mod_recall = test_model_expt1(order$recall, par)
  
  return(sum((mod_confirm - order$confirm$HumanItemAcc)^2) + 
           sum(mod_recall - order$recall$HumanItemAcc)^2)
}

fit_model_expt1 <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt1, ord=order, 
                    human_perf=unlist(order$recall$HumanItemAcc),
                    lower=par_lower, upper=par_upper)
  
    cat(model_name,'\t',order$Condition,'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}
```

```{r fit_expt1}
expt1_confirm_fit <- fit_model_expt1_condition("kachergis", expt1_confirm, c(.001,.1,.5), c(5,15,1))
expt1_recall_fit <- fit_model_expt1_condition("kachergis", expt1_recall, c(.001,.1,.5), c(5,15,1))
expt1_fit <- fit_model_expt1("kachergis", expt1_input, c(.001, .1, .5), c(5, 15, 1))

```

```{r run_expt1}
expt1_confirm_fubg <- test_model_expt1(expt1_confirm, 
                                       c(0.1308011, 0.1, 0.9214806))
expt1_recall_fubg <- test_model_expt1(expt1_recall, 
                                      c(3.369119, 6.154075, 0.7255642))
expt1_fubg_confirm <- test_model_expt1(expt1_confirm, c(5, 8.050791, 1))
expt1_fubg_recall <- test_model_expt1(expt1_recall, c(5, 8.050791, 1))
```

```{r expt1_fubg_results}
paste0(round(c(mean(expt1_confirm_fubg[1,1:4]),
               mean(expt1_confirm_fubg[1,5:8]),
               mean(expt1_confirm_fubg[1,9:14])),
             4), collapse=", ")

paste0(round(c(mean(expt1_recall_fubg[1,1:4]),
               mean(expt1_recall_fubg[1,5:8]),
               mean(expt1_recall_fubg[1,9:14])),
             4), collapse=", ")

paste0(round(c(mean(expt1_fubg_confirm[1,1:4]),
               mean(expt1_fubg_confirm[1,5:8]),
               mean(expt1_fubg_confirm[1,9:14])),
             4), collapse=", ")

paste0(round(c(mean(expt1_fubg_recall[1,1:4]),
               mean(expt1_fubg_recall[1,5:8]),
               mean(expt1_fubg_recall[1,9:14])),
             4), collapse=", ")
```

## Expt 3

### Input
```{r expt3_input_words}
expt3_words <- matrix(c(63, 64, 65, 66, 67,
                        68, 69, 70, 71, 72,
                        59, 60, 61, 62,
                        59, 60, 61, 62,
                        59, 60, 61, 62,
                        63, 64, 65, 66, 67,
                        68, 69, 70, 71, 72,
                        63, 64, 65, 66, 67,
                        68, 69, 70, 71, 72
                        ),
                        nrow = 42,
                        ncol=1, byrow=T
                        )
```

```{r expt3_input_ppa_obj}
expt3_ppa_obj <- matrix(c(31, 63, 30, 29, 34, 64, 33, 32, 
                          37, 65, 36, 35, 40, 66, 39, 38,
                          43, 67, 42, 41, 46, 68, 45, 44, 
                          49, 69, 48, 47, 52, 70, 51, 50,
                          55, 71, 54, 53, 58, 72, 57, 56,
                          
                          59, 7, 6, 5, 60, 14, 13, 12,
                          61, 21, 20, 19, 62, 28, 27, 26,
                          
                          59, 30, 33, 36, 60, 39, 42, 45,
                          61, 48, 51, 54, 62, 57, 29, 32,
                          
                          4, 3, 2, 1, 11, 10, 9, 8, 
                          18, 17, 16, 15, 25, 24, 23, 22, 
                          
                          63, 3, 38, 41, 64, 44, 23, 17,
                          65, 16, 56, 4, 66, 11, 18, 25,
                          67, 47, 10, 50, 68, 24, 2, 9,
                          69, 53, 35, 1, 70, 8, 14, 22,
                          71, 14, 30, 41, 72, 28, 44, 20,
                          
                          63, 48, 13, 7, 64, 6, 51, 4,
                          65, 20, 57, 54, 66, 6, 56, 50,
                          67, 47, 27, 12, 68, 36, 11, 27,
                          69, 18, 5, 33, 70, 26, 19, 12, 
                          71, 20, 38, 29, 72, 53, 44, 25
                      ),
                    nrow = 42,
                    ncol=4, byrow=T
)

```

```{r expt3_input_app_obj}
expt3_app_obj <- matrix(c(31, 63, 30, 29, 34, 64, 33, 32, 
                          37, 65, 36, 35, 40, 66, 39, 38,
                          43, 67, 42, 41, 46, 68, 45, 44, 
                          49, 69, 48, 47, 52, 70, 51, 50,
                          55, 71, 54, 53, 58, 72, 57, 56,
                          
                          4, 3, 2, 1, 11, 10, 9, 8, 
                          18, 17, 16, 15, 25, 24, 23, 22, 
                          
                          59, 7, 6, 5, 60, 14, 13, 12,
                          61, 21, 20, 19, 62, 28, 27, 26,
                          
                          59, 30, 33, 36, 60, 39, 42, 45,
                          61, 48, 51, 54, 62, 57, 29, 32,
                          
                          63, 3, 38, 41, 64, 44, 23, 17,
                          65, 16, 56, 4, 66, 11, 18, 25,
                          67, 47, 10, 50, 68, 24, 2, 9,
                          69, 53, 35, 1, 70, 8, 14, 22,
                          71, 14, 30, 41, 72, 28, 44, 20,
                          
                          63, 48, 13, 7, 64, 6, 51, 4,
                          65, 20, 57, 54, 66, 6, 56, 50,
                          67, 47, 27, 12, 68, 36, 11, 27,
                          69, 18, 5, 33, 70, 26, 19, 12, 
                          71, 20, 38, 29, 72, 53, 44, 25
),
nrow = 42,
ncol=4, byrow=T
)

```

```{r expt3_input}
expt3_app_train <- list("words" = expt3_words, "objs" = expt3_app_obj)
expt3_app <- list("train" = expt3_app_train, "Nsubj" = 40, "Condition" = "Conflict-first",
              "HumanItemAcc" = c(# Filler
                                 0.25, 0.275, 0.275, 0.275, 0.225, 
                                 0.2, 0.25, 0.275, 0.125, 0.15,
                                 # Target
                                 0.45, 0.275, 0.225, 0.3))
expt3_ppa_train <- list("words" = expt3_words, "objs" = expt3_ppa_obj)
expt3_ppa <- list("train" = expt3_ppa_train, "Nsubj" = 40, "Condition" = "Confirm-first",
                     "HumanItemAcc" = c(# Filler
                                        0.268, 0.268, 0.268, 0.512, 0.268, 
                                        0.293, 0.390, 0.317, 0.220, 0.268,
                                        # Target
                                        0.292, 0.488, 0.317, 0.390))


```

### Test
```{r expt3_test}
expt3_test <- matrix(c(
  63, 31, 30, 29,  3, 38, 41, 48, 13,  7, 43, 61,
  64, 34, 33, 32, 44, 23, 17,  6, 51,  4, 67, 58,
  65, 37, 36, 35, 16, 56,  4, 20, 57, 54, 66, 55,
  66, 40, 39, 38, 11, 18, 25,  6, 56, 50, 59, 71,
  67, 43, 42, 41, 47, 10, 50, 47, 27, 12, 64, 31,
  68, 46, 45, 44, 24,  2,  9, 36, 11, 27, 60, 72,
  69, 49, 48, 47, 53, 35,  1, 18,  5, 33, 34, 62,
  70, 52, 51, 50,  8, 14, 22, 26, 19, 12, 37, 63,
  71, 55, 54, 53, 14, 30, 41, 20, 38, 29, 65, 70,
  72, 58, 57, 56, 28, 44, 20, 53, 44, 25, 40, 52,
  
  59,  7,  6,  5, 30, 33, 36,  4,  3,  2,  1, 68,
  60, 14, 13, 12, 39, 42, 45, 11, 10,  9,  8, 49,
  61, 21, 20, 19, 48, 51, 54, 18, 17, 16, 15, 69,
  62, 28, 27, 26, 57, 29, 32, 25, 24, 23, 22, 52
),
nrow = 14,
ncol = 12, byrow = T)
```

```{r expt3_test_fn}
test_model_expt3 <- function(expt, params) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[42][[1]]

  test_performance = matrix(0, 1, 14)
  for(test_row in 1:nrow(expt3_test)) {
    test_options = as.integer(expt3_test[test_row,])
    numerator = final_trajectory[test_options[1], test_options[1]]
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_options[1], option]
    }
    test_performance[1,test_row] = numerator / denominator
  }
                      
  return(test_performance)
}
```

### Fit model
```{r expt3_fit_model}
meanSSE_expt3 <- function(par, order, human_perf) {
  mod = test_model_expt3(order, par)
  return(sum((mod-human_perf)^2))
}

fit_model_expt3 <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt3, ord=order, human_perf=unlist(order$HumanItemAcc), lower=par_lower, upper=par_upper) 
    
    cat(model_name,'\t',order$Condition,'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}
```

```{r fit_expt3}
expt3_app_fit <- fit_model_expt3("kachergis", expt3_app, c(.001,.1,.5), c(5,15,1)) 

expt3_ppa_fit <- fit_model_expt3("kachergis", expt3_ppa, c(.001,.1,.5), c(5,15,1)) 
```

### Run model
```{r expt3_run_models}
run_expt3 <- function(app_param, ppa_param) {
  app <- test_model_expt3(expt3_app, app_param)
  ppa <- test_model_expt3(expt3_ppa, ppa_param)
  
  all <- c(mean(app[11:14]), mean(app[1:10]), mean(ppa[11:14]), mean(ppa[1:10]))
  print(paste0(round(app, 3), collapse=", "))
  print(paste0(round(ppa, 3), collapse=", "))
  print(paste0(round(all, 3), collapse=", "))
  return(paste0(round(all, 3), collapse=", "))
}

run_expt3(c(1.115341, 4.213643, 0.9088536), c(5, 6.193, 0.929))
run_expt3(c(5, 5.495327, 0.905484 ), c(5, 6.193, 0.929))
```

```{r expt3_fit_to_expt}
meanSSE_expt3_all <- function(par, order, human_perf) {
  ppa_mod = test_model_expt3(order$ppa, par)
  app_mod = test_model_expt3(order$app, par)
  return(sum((ppa_mod-order$ppa$HumanItemAcc)^2)+sum((app_mod-order$app$HumanItemAcc)^2))
}

fit_model_expt3_all <- function(model_name, order, par_lower, par_upper) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    best <- psoptim(par_init, meanSSE_expt3_all, ord=order, human_perf=unlist(order$ppa$HumanItemAcc), lower=par_lower, upper=par_upper) 
    
    cat(model_name,'\t',order$Condition,'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}

expt3_all <- list("app" = expt3_app, "ppa" = expt3_ppa, "Condition" = "Expt 3")

expt3_fit <- fit_model_expt3_all("kachergis", expt3_all, c(.001,.1,.5), c(5,15,1)) 

```

```{r expt3}

run_expt3(c(5, 5.936, 0.919), c(5, 5.936, 0.919))
```

## Expt 4

### Input
```{r expt4_words}
expt4_words <- matrix(c(5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                        1, 2, 3, 4, 
                        1, 2, 3, 4, 
                        1, 2, 3, 4,
                        5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                        5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                        15, 16, 17, 18, 
                        15, 16, 17, 18,  
                        15, 16, 17, 18),
                      nrow = 54,
                      ncol=1, byrow=T
)

```

```{r expt4_obj}
# Same and switch are basically the same in the FUbG input,
# because there's one item that co-occurs all 3 times, one item
# that co-occurs twice, and the rest co-occur once.
expt4_obj <- matrix(c(5, 35, 36, 37,  6, 39, 40, 41,  
                     7, 43, 44, 45,  8, 47, 48, 49,
                     9, 51, 52, 53,  10, 55, 56, 57,  
                     11, 59, 60, 61,  12, 63, 64, 65, 
                     13, 67, 68, 69,  14, 71, 72, 73,  
                       
                     1, 19, 20, 21,  2, 23, 24, 25,  
                     3, 27, 28, 29,  4, 31, 32, 33,
                     1, 19, 30, 24,  2, 23, 22, 33,  
                     3, 27, 34, 21,  4, 31, 26, 29,
                     1, 27, 33, 26,  2, 19, 29, 34,  
                     3, 31, 24, 22,  4, 23, 20, 30,
                     
                     5, 36, 62, 57,  6, 40, 70, 61,   
                     7, 44, 54, 73,  8, 48, 42, 65,
                     9, 52, 66, 45,  10, 56, 38, 69,  
                     11, 60, 50, 41,  12, 64, 46, 49,
                     13, 68, 74, 37,  14, 72, 58, 53,
                     
                     5,  48, 69, 54,  6, 44, 53, 58,   
                     7, 36, 41, 50,  8, 52, 37, 46, 
                     9, 40, 61, 74,  10, 72, 45, 62,  
                     11, 64, 73, 70,  12, 68, 57, 42,
                     13, 56, 49, 66,  14, 60, 65, 38,
                       
                     15, 75, 76, 77,  16, 79, 80, 81,  
                     17, 83, 84, 85,  18, 87, 88, 89,
                     15, 75, 86, 80,  16, 79, 78, 88,  
                     17, 83, 90, 76,  18, 87, 82, 84,
                     15, 83, 88, 78,  16, 75, 84, 90,  
                     17, 87, 80, 78,  18, 83, 76, 86
                           ),
                      nrow = 54,
                      ncol=4, byrow=T
)

```

```{r expt4_input}
expt4_train <- list("words" = expt4_words, "objs" = expt4_obj)
expt4_input <- list("train" = expt4_train, "Nsubj" = 40,
                           "switch_human" = c(0.35, 0.575, 0.3, 0.275, 
                                 0.35, 0.425, 0.425, 0.4, 0.35, 
                                 0.275, 0.475, 0.475, 0.55, 0.425, 
                                 0.275, 0.325, 0.4, 0.55
                                 ),
                           "same_human" = c(0.585, 0.488, 0.756, 0.683, 
                                 0.415, 0.512, 0.39, 0.854, 0.61, 
                                 0.317, 0.902, 0.878, 0.488, 0.341, 
                                 0.39, 0.439, 0.61, 0.854
                                 ),
                    "Condition" = "Toilet")
```

### Test
```{r expt4_test}
expt4_test_obj_same <- matrix(c(
  15, 75, 86, 82, 60, 33,  5, 10, 44,
  16, 79, 78, 90, 64,  6, 48, 11, 59,
  17, 83, 90, 78, 68, 49, 53, 32, 12,
  18, 87, 82, 86, 72, 41, 57, 13, 67,
  
   5, 35, 62, 54, 20, 45, 63, 15, 71,
   6, 39, 70, 58, 24, 60, 68, 16, 17,
   7, 43, 54, 50, 28, 55, 14, 84, 69,
   8, 47, 42, 38, 32, 25, 20, 21, 52,
   9, 51, 66, 90, 76,  1, 72, 39, 27,
  10, 55, 38, 62, 80, 49, 29, 75, 89,
  11, 59, 50, 70, 84, 31, 23, 43, 87,
  12, 63, 46, 42, 88,  3, 35, 79, 24,
  13, 67, 74, 66, 36, 19, 28, 51, 88,
  14, 71, 58, 38, 40,  4, 47, 76, 81,
  
   1, 19, 30, 26, 44,  9, 65, 80, 18,
   2, 23, 22, 34, 48, 36, 56, 77, 83,
   3, 27, 34, 22, 52, 61, 37, 73,  2,
   4, 31, 26, 30, 56, 40, 64,  7, 85
  ),
  nrow = 18,
  ncol = 9, byrow = T)

expt4_test_obj_switch <- matrix(c(
  15, 75, 86, 82, 60, 33,  5, 10, 44,
  16, 79, 78, 90, 64,  6, 48, 11, 59,
  17, 83, 90, 78, 68, 49, 53, 32, 12,
  18, 87, 82, 86, 72, 41, 57, 13, 67,
  
   5, 35, 62, 54, 20, 45, 63, 75, 71,
   6, 39, 70, 58, 24, 60, 68, 16, 83,
   7, 43, 54, 50, 28, 55, 14, 84, 69,
   8, 47, 42, 38, 32, 25, 20, 21, 52,
   9, 51, 66, 90, 76, 19, 72, 39,  3,
  10, 55, 38, 62, 80, 49, 29, 15, 89,
  11, 59, 50, 70, 84, 31,  2, 43, 18,
  12, 63, 46, 42, 88, 27, 35, 79, 24,
  13, 67, 74, 66, 36,  1, 28, 51, 88,
  14, 71, 58, 38, 40,  4, 47, 76, 81,
  
   1, 19, 30, 26, 44,  9, 65, 80, 87,
   2, 23, 22, 34, 48, 36, 56, 77, 17,
   3, 27, 34, 22, 52, 61, 37, 73, 23,
   4, 31, 26, 30, 56, 40, 64,  7, 85
  ),
  nrow = 18,
  ncol = 9, byrow = T)
```

```{r expt4_test_fn}
test_model_expt4 <- function(expt, params, same=T) {
  mod = run_model(expt, params, print_perf=F)
  final_trajectory = mod$traj[54][[1]]

  test_performance = matrix(0, 1, 18)
  for(test_row in 1:18) {
    if(same == TRUE) {
      test_options = as.integer(expt4_test_obj_same[test_row,])
    } else {
      test_options = as.integer(expt4_test_obj_switch[test_row,])
    }
    
    numerator = final_trajectory[test_options[1], test_options[1]]
    denominator = 0
    for(option in test_options) {
      denominator = denominator + final_trajectory[test_options[1], option]
    }
    test_performance[1,test_row] = numerator / denominator
  }
                      
  return(test_performance)
}

```

### Fit
```{r expt4_fit_fn}
meanSSE_expt4_same <- function(par, order, human_perf) {
  mod = test_model_expt4(order, par, same=TRUE)
  return(sum((mod-human_perf)^2))
}

meanSSE_expt4_switch <- function(par, order, human_perf) {
  mod = test_model_expt4(order, par, same=FALSE)
  return(sum((mod-human_perf)^2))
}

meanSSE_expt4 <- function(par, order, human_perf) {
  mod_same = test_model_expt4(order, par, same=TRUE)
  mod_switch = test_model_expt4(order, par, same=FALSE)
  return(sum((mod_same-order$same_human)^2)+
           sum((mod_switch-order$switch_human)^2))
}

fit_model_expt4 <- function(model_name, order, par_lower, par_upper, same=TRUE, expt=FALSE) {
  par_init = (par_lower + par_upper) / 2
  startt = Sys.time()
  cat("Model\tOrder\tSSE\tParameters\n")
  for(test_row in 1:10) { 
    if(expt == TRUE) {
      best <- psoptim(par_init, 
                      meanSSE_expt4, 
                      ord=order,
                      human_perf=unlist(order$same_human),
                      lower=par_lower, upper=par_upper) 
    } else{
      if(same == TRUE) {
        best <- psoptim(par_init, 
                        meanSSE_expt4_same, 
                        ord=order,
                        human_perf=unlist(order$same_human),
                        lower=par_lower, upper=par_upper) 
      } else {
        best <- psoptim(par_init, 
                        meanSSE_expt4_switch, 
                        ord=order,
                        human_perf=unlist(order$switch_human),
                        lower=par_lower, upper=par_upper) 
        
      }
    }
    
    cat(model_name,'\t',"expt 4",'\t',best$value,'\t',best$par,'\n')
  }
  stopt = Sys.time()
  print(stopt-startt)
}

```

```{r expt4_fit}
expt4_same_fit <- fit_model_expt4("kachergis", expt4_input, c(.001,.1,.5), c(5,15,1), same=TRUE, expt=FALSE) 

expt4_switch_fit <- fit_model_expt4("kachergis", expt4_input, c(.001,.1,.5), c(5,15,1), same=FALSE, expt=FALSE) 

expt4_fit <- fit_model_expt4("kachergis", expt4_input, c(.001,.1,.5), c(5, 15, 1), same=FALSE, expt=TRUE)
```

### Run models
```{r expt4_run_fn}
run_expt4 <- function(same_param, switch_param) {
  same <- test_model_expt4(expt4_input, same_param)
  switch <- test_model_expt4(expt4_input, switch_param)
  
  all <- c(mean(same[1:4]), mean(same[15:18]), mean(same[5:14]),
           mean(switch[1:4]), mean(switch[15:18]), mean(switch[5:14]))
  print(paste0(round(same, 3), collapse=", "))
  print(paste0(round(switch, 3), collapse=", "))
  return(paste0(round(all, 3), collapse=", "))
}

```

```{r expt4_run}
print("tuned to each condition")
run_expt4(c(0.140, 0.1, 0.895), c(0.0467, 0.1, 0.975))

print("tuned to expt")
run_expt4(c(0.0765, 0.1, 0.936),c(0.0765, 0.1, 0.936))
```

